# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageA: 'delivery-API'
  imageD: 'delivery-client'
  latestTagA: '$(imageA):latest'
  latestTagD: '$(imageD):latest'

steps:
- script: |
    docker build -f Dockerfile -t $(dockerId).azurecr.io/$(latestTagA) .
    docker login -u $(dockerId) -p $(pswd) $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(latestTag)
  displayName: 'dAPI'
- script: |
    docker build -f src/client/Dockerfile-client -t $(dockerId).azurecr.io/$(latestTagD) ./src/client
    docker login -u $(dockerId) -p $(pswd) $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(latestTag)
  displayName: 'dclient'
