version: "3.5"
services:
  api:
    container_name: delivery_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '22000:80'
    networks: 
      - deliverynet


  delivery_client:
    container_name: delivery_client
    build:
      context: ./src/client
      dockerfile: Dockerfile-client
    networks: 
      - deliverynet

networks: 
  deliverynet:
    driver: bridge
    name: delivery_net

